name: Deploy to Production

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_YOUTUBE_API_KEY: ${{ secrets.VITE_YOUTUBE_API_KEY }}
          
      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: decloud2376.zahid.host
          port: 32762
          username: youtubebatchuploaderfun
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/*"
          target: "/home/youtubebatchuploaderfun/www"
          strip_components: 1 