name: Deploy to Production

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_YOUTUBE_API_KEY: ${{ secrets.VITE_YOUTUBE_API_KEY }}
          VITE_GOOGLE_CLIENT_SECRET: ${{ secrets.VITE_GOOGLE_CLIENT_SECRET }}
          VITE_GOOGLE_REFRESH_TOKEN: ${{ secrets.VITE_GOOGLE_REFRESH_TOKEN }}
          VITE_GOOGLE_ACCESS_TOKEN: ${{ secrets.VITE_GOOGLE_ACCESS_TOKEN }}
          
      - name: Create .env file
        run: |
          echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> .env
          echo "VITE_YOUTUBE_API_KEY=${{ secrets.VITE_YOUTUBE_API_KEY }}" >> .env
          echo "VITE_GOOGLE_CLIENT_SECRET=${{ secrets.VITE_GOOGLE_CLIENT_SECRET }}" >> .env
          echo "VITE_GOOGLE_REFRESH_TOKEN=${{ secrets.VITE_GOOGLE_REFRESH_TOKEN }}" >> .env
          echo "VITE_GOOGLE_ACCESS_TOKEN=${{ secrets.VITE_GOOGLE_ACCESS_TOKEN }}" >> .env
          
      - name: Debug Environment
        run: |
          echo "Checking environment variables..."
          echo "VITE_GOOGLE_CLIENT_ID exists: ${{ secrets.VITE_GOOGLE_CLIENT_ID != '' }}"
          echo "VITE_YOUTUBE_API_KEY exists: ${{ secrets.VITE_YOUTUBE_API_KEY != '' }}"
          echo "VITE_GOOGLE_CLIENT_SECRET exists: ${{ secrets.VITE_GOOGLE_CLIENT_SECRET != '' }}"
          echo "VITE_GOOGLE_REFRESH_TOKEN exists: ${{ secrets.VITE_GOOGLE_REFRESH_TOKEN != '' }}"
          echo "VITE_GOOGLE_ACCESS_TOKEN exists: ${{ secrets.VITE_GOOGLE_ACCESS_TOKEN != '' }}"
          
      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: decloud2376.zahid.host
          port: 32762
          username: youtubebatchuploaderfun
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/*"
          target: "/home/youtubebatchuploaderfun/www"
          strip_components: 1 